### ISSUE TITLE
PropagateAtLaunch Required For Common Tag In AutoScalingGroup

### ISSUE THREAD

**Issue by dchukhin** [caktus/aws-web-stacks#103]
The [common tags](https://github.com/caktus/aws-web-stacks/blob/develop/stack/tags.py#L5) work fine, unless they are used for an AutoScalingGroup, which requires `PropagateAtLaunch` to be defined. If using the common tag as is, it fails with a `PropagateAtLaunch not found in properties` error.

Some resources:
 - a pull request to fix this issue in the `amazon-guardduty-tester` library: https://github.com/awslabs/amazon-guardduty-tester/pull/11
 - troposphere's use of `troposphere.autoscaling.Tag` , rather than `troposphere.Tag`: https://github.com/cloudtools/troposphere/blob/master/examples/Autoscaling.py

**Comment by tobiasmcnulty** [comment]
@dchukhin Thanks for 👀 into that! Using `autoscaling.Tag` instead of a `troposphere.Tag` required that `PropagateAtLaunch` and helped avoid the later error.
