### ISSUE TITLE
v2.0: CloudFormation resources to rename

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/aws-web-stacks#34]
As the stack gets built out, some resource names in the CloudFormation stack are being left as-is for backwards compatibility reasons. At some point, it'd be nice to clean those up so they match the current stack configuration. This ticket is intended to keep a running list of those resources.

- [x] `PostgreSQL` should be renamed to `Database` (or similar)
- [ ] all resources with the word `Container` in them (perhaps `Web`) would be better
- [ ] `AssetsBucket` and `PrivateAssetsBucket`: usage of these buckets varies depending on the application. Perhaps `StaticAssetsBucket` and `DynamicAssetsBucket` would be better.

**Comment by cchurch** [comment]
`PostgreSQL` to `DatabaseInstance` changed in ff16ae091045fba0f28bd9bc9ab223d598d2ea98.

**Comment by tobiasmcnulty** [comment]
2.0 is released, so closing this out.
