### ISSUE TITLE
GDPR/WHOIS certificate validation issues

### ISSUE THREAD

**Issue by vkurup** [caktus/aws-web-stacks#46]
To comply with GDPR, domain registrars have stopped including email addresses in WHOIS query results. It's not consistent across the board, but here is an example from moniker.com: https://faq.moniker.com/my-account/european-general-data-protection-regulation-gdpr

Currently aws-web-stacks tells AWS to validate the requested domain using 'email validation'. AWS sends the email an email to 5 specified accounts at the domain in question (like 'admin', 'webmaster', etc) and then also to the 3 emails listed as the Registrant, Technical, and Administrative contact in WHOIS. Those last 3 will no longer be available if the registrar is now hiding them. If you happen to have mail set up for the domain, then you're OK because one of the first 5 accounts should receive the email.

If not, however, the email will never get to you, cert approval will fail, and the stack will get rolled back. For subdomains like foo.example.com, you're probably not going to want to set up a MX record for each subdomain.

I'm not sure of the best solution, but wanted to open up this issue to track it.

**Comment by tobiasmcnulty** [comment]
DNS validation is now supported! 🙌
