### ISSUE TITLE
Dokku Stack: Unresolved resource dependencies [WebWorkerHealthCheckPort

### ISSUE THREAD

**Issue by thomasklein-winemaker** [caktus/aws-web-stacks#98]
Indeed, [dokku-no-nat.yaml](https://s3.amazonaws.com/aws-web-stacks/dokku-no-nat.yaml) does not resolve the reference to WebWorkerHealthCheckPort. Is the best way to introduce this value manually?

**Comment by quentinbrohan** [comment]
Have you found a solution since ?

**Comment by tobiasmcnulty** [comment]
Thanks for the report! This should be fixed in the forthcoming 2.1.0 release.

Please note we do not have the bandwidth to keep maintaining the Dokku stack long-term, so it will probably be removed at some point.
